### ISSUE TITLE
Random Crashing issues

### ISSUE THREAD

**Issue by iRobsie** [kaleidocli/BozjaBuddy#22]
I know a new patch just dropped, but I've been having issues with Bozja Buddy for a little while now. It's not anything constant, or even an all the time thing. I'm not usually doing anything in specific, nor am I even in bozja whenever it happens, but it usually gives me the crash dalamud error when it does. I believe I have a few more tspack files laying around I can look for, but as for now here's the recent one I was meaning to send this way.
[BOZJA BUDDY PLEASE.zip](https://github.com/kaleidocli/BozjaBuddy/files/12292255/BOZJA.BUDDY.PLEASE.zip)

**Comment by kaleidocli** [comment]
Thank you for the report!
Fixed: https://github.com/kaleidocli/BozjaBuddy/commit/db242802be5bd0a41794ff42c80977ebe1f6ceb0
